### PR TITLE
Fixes from testing

### LINKED ISSUE #25: Test provider and relayer package on prod

### PR DESCRIPTION
**Pull request by pablocampogo**
- Do various fixes to provider package, mainly structures fixes and adding optional parameters to some functions.
- Delete `GetNewSession` func from relayer package since its use was difficult from client side, now clients will user provider package's `Dispatch` function directly.
- Change `RelayResponse` to be a struct instead of a plain string for ease of usage.

Closes #25 
Close T-2753

### CODE REVIEW

File: pkg/provider/options.go [hunk 1]
```diff
@@ -48,3 +55,8 @@ type DispatchRequestOptions struct {
 type RelayRequestOptions struct {
 	RejectSelfSignedCertificates bool
 }
+
+// GetTransactionOptions represents optional arguments for GetTransaction request
```
Comment (rem1niscence) [inline pkg/provider/options.go:59]:
```suggestion
// GetTransactionOptions represents the optional arguments for a GetTransaction request
```

File: pkg/provider/relay.go [hunk 2]
```diff
@@ -13,6 +13,12 @@ type Relay struct {
 	Proof   *RelayProof   `json:"proof"`
 }
 
+// RelayResponse reprensents Relay RPC response
```
Comment (rem1niscence) [inline pkg/provider/relay.go:16]:
```suggestion
// RelayResponse reprensents the Relay RPC response
```

**Review by rem1niscence — APPROVED** [review]
